package week2;

public class ExSampleExceptionThrow 
{
	public static void main(String args[])
	{
		int num=10;
		int num1=0;
		int div;
		if(num>20)
		{			throw new ArithmeticException("one");
}
		try{  
			// It is used to throw custom exception
			
			   
			  }  
			  catch(ArithmeticException e)
			  {
				  System.out.println(e+"yes");
				  }

}
}
